# This is a basic workflow to help you get started with Actions
on:
  pull_request:
    types:
      # Check title when opened.
      - opened
      - edited
      # Check title when new commits are pushed.
      # Required to use as a status check.
      - synchronize

jobs:
  cpp_style_check:
    runs-on: ubuntu-latest
    name: Check C++ Style
    steps:
    - name: Checkout this commit
      uses: actions/checkout@v2
    - name: Run style checks
      uses: coleaeason/actions-uncrustify@v1
      with: 
        configPath: 'style.cfg'
  publish:
    runs-on: ubuntu-latest
    name: PR title check
    steps:
      - uses: actions/checkout@v1
      - uses: deepakputhraya/action-pr-title@master
        with:
          # Match pull request titles in the form [RA-1234] Message.
          regex: '^\[[A-Z]+\-[0-9]+\]'
